Repository krypt-project/krypt-frontend, pull requests merged in 2025-09, with the labels that each got.

#6 5 fix sidebar buttons colliding
  mindvault-app/src/app/dashboard/components/Sidebar.tsx
  mindvault-app/src/components/atoms/Button.tsx
Labels: bug

#8 Création des fichiers pour les variables d'environnement
  mindvault-app/src/app/dashboard/components/Sidebar.tsx
  mindvault-app/src/app/login-register/components/AuthCard.tsx
  mindvault-app/src/utils/api.ts
Labels: documentation, enhancement

#16 15 fix correction des bugs
  krypt-app/.vscode/launch.json
  krypt-app/src/app/dashboard/components/EditorArea.tsx
  krypt-app/src/app/dashboard/components/EditorHeader.tsx
  krypt-app/src/app/landing/components/Hero.tsx
  krypt-app/src/styles/globals.css
Labels: bug

#19 18 feat créer la page billing
  krypt-app/src/app/account-verified/page.tsx
  krypt-app/src/app/billing/components/BillingCard.tsx
  krypt-app/src/app/billing/components/BillingModal.tsx
  krypt-app/src/app/billing/page.tsx
  krypt-app/src/app/landing/components/Header.tsx
  krypt-app/src/app/login-register/components/AuthCard.tsx
  krypt-app/src/app/login-register/components/RegisterForm.tsx
  krypt-app/src/app/login-register/page.tsx
  krypt-app/src/components/atoms/Badge.tsx
  krypt-app/src/components/atoms/Button.tsx
  krypt-app/src/components/atoms/Card.tsx
  krypt-app/src/components/atoms/Modal.tsx
  krypt-app/src/components/feedback/Loader.tsx
  krypt-app/src/components/feedback/Stepper.tsx
  krypt-app/src/config/constants.tsx
  krypt-app/src/styles/globals.css
Labels: enhancement, frontend

#28 27 feat display user related data with account page and settings
  krypt-app/public/profil.png
  krypt-app/src/app/dashboard/components/ActivityBar.tsx
  krypt-app/src/app/dashboard/components/settings/AccountSettings.tsx
  krypt-app/src/app/dashboard/components/settings/AppearanceSettings.tsx
  krypt-app/src/app/dashboard/page.tsx
  krypt-app/src/components/atoms/Popup.tsx
  krypt-app/src/styles/globals.css
Labels: frontend

#35 26 tests unitaire atoms
  krypt-app/.env.example
  krypt-app/.eslintrc.json
  krypt-app/generate-test.ts
  krypt-app/jest.config.ts
  krypt-app/jest.setup.ts
  krypt-app/package-lock.json
  krypt-app/package.json
  krypt-app/src/app/account-verified/page.tsx
  krypt-app/src/app/billing/components/BillingCard.tsx
  krypt-app/src/app/billing/components/BillingModal.tsx
  krypt-app/src/app/billing/page.tsx
  krypt-app/src/app/dashboard/components/ActivityBar.tsx
  krypt-app/src/app/dashboard/components/SidebarNotes.tsx
  krypt-app/src/app/dashboard/components/SidebarSettings.tsx
  krypt-app/src/app/dashboard/components/editor/EditorArea.tsx
  krypt-app/src/app/dashboard/components/editor/EditorHeader.tsx
  krypt-app/src/app/dashboard/components/editor/QuickAccessPopup.tsx
  krypt-app/src/app/dashboard/components/home/HomeDashboard.tsx
  krypt-app/src/app/dashboard/page.tsx
  krypt-app/src/app/landing/components/CTA.tsx
  krypt-app/src/app/landing/components/Header.tsx
  krypt-app/src/app/landing/components/Hero.tsx
  krypt-app/src/app/login-register/components/AuthCard.tsx
  krypt-app/src/app/login-register/components/LoginForm.tsx
  krypt-app/src/app/login-register/components/RegisterForm.tsx
  krypt-app/src/app/login-register/page.tsx
  krypt-app/src/components/atoms/Badge/Badge.tsx
  krypt-app/src/components/atoms/Badge/__test__/Badge.auto.test.tsx
  krypt-app/src/components/atoms/Badge/__test__/Badge.test.tsx
  krypt-app/src/components/atoms/Button/Button.tsx
  krypt-app/src/components/atoms/Button/__test__/Button.auto.test.tsx
  krypt-app/src/components/atoms/Button/__test__/Button.test.tsx
  krypt-app/src/components/atoms/Card/Card.tsx
  krypt-app/src/components/atoms/Card/__test__/Card.auto.test.tsx
  krypt-app/src/components/atoms/Modal.tsx
  krypt-app/src/components/molecules/FeatureCard.tsx
  krypt-app/src/components/molecules/FooterSection.tsx
  krypt-app/tsconfig.json
Labels: enhancement

#37 fix generate test
  krypt-app/generate-test.ts
  krypt-app/src/app/dashboard/components/SidebarNotes.tsx
  krypt-app/src/app/dashboard/components/SidebarSettings.tsx
  krypt-app/src/app/dashboard/components/editor/EditorArea.tsx
  krypt-app/src/app/dashboard/components/editor/EditorHeader.tsx
  krypt-app/src/app/login-register/components/LoginForm.tsx
  krypt-app/src/app/login-register/components/RegisterForm.tsx
  krypt-app/src/components/atoms/Badge/__test__/Badge.auto.test.tsx
  krypt-app/src/components/atoms/Badge/__test__/Badge.test.tsx
  krypt-app/src/components/atoms/Badge/__test__/__snapshots__/Badge.auto.test.tsx.snap
  krypt-app/src/components/atoms/Button/__test__/Button.auto.test.tsx
  krypt-app/src/components/atoms/Button/__test__/Button.test.tsx
  krypt-app/src/components/atoms/Button/__test__/__snapshots__/Button.auto.test.tsx.snap
  krypt-app/src/components/atoms/Card/__test__/Card.auto.test.tsx
  krypt-app/src/components/atoms/Card/__test__/__snapshots__/Card.auto.test.tsx.snap
  krypt-app/src/components/atoms/Input/Input.tsx
  krypt-app/src/components/atoms/Input/__test__/Input.auto.test.tsx
  krypt-app/src/components/atoms/Input/__test__/__snapshots__/Input.auto.test.tsx.snap
  krypt-app/src/components/molecules/ChatBotInterface.tsx
Labels: bug
